version: '3.8'

services:
  error_handling_service:
    build: ./error_handling_service
    ports:
      - "8005:8005"
    depends_on:
      - agent_service
      - booking_service
      - sales_service
      - invoicing_service
      - train_booking_service
      - train_seat_status_service

  agent_service:
    build: ./agent_service
    ports:
      - "8000:8000"
    environment:
      - AGENT_SERVICE_URL=http://agent_service:8000
      - ERROR_HANDLING_SERVICE_URL=http://error_handling_service:8005

  booking_service:
    build: ./booking_service
    ports:
      - "8001:8001"
    depends_on:
      - agent_service
    environment:
      - AGENT_SERVICE_URL=http://agent_service:8000
      - ERROR_HANDLING_SERVICE_URL=http://error_handling_service:8005

  sales_service:
    build: ./sales_service
    ports:
      - "8002:8002"
    depends_on:
      - booking_service
    environment:
      - ERROR_HANDLING_SERVICE_URL=http://error_handling_service:8005

  invoicing_service:
    build: ./invoicing_service
    ports:
      - "8003:8003"
    depends_on:
      - booking_service
    environment:
      - ERROR_HANDLING_SERVICE_URL=http://error_handling_service:8005

  train_booking_service:
    build: ./train_booking_service
    ports:
      - "8084:8084"
    depends_on:
      - agent_service
      - booking_service
    environment:
      - AGENT_SERVICE_URL=http://agent_service:8000
      - BOOKING_SERVICE_URL=http://booking_service:8001
      - ERROR_HANDLING_SERVICE_URL=http://error_handling_service:8005

  train_seat_status_service:
    build: ./train_seat_status_service
    ports:
      - "8090:8090"
    depends_on:
      - train_booking_service
    environment:
      - TRAIN_BOOKING_SERVICE_URL=http://train_booking_service:8084
      - ERROR_HANDLING_SERVICE_URL=http://error_handling_service:8005